#配置文件
Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 6000
  WriteTimeout: 6000
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: 123456  # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: douyin_service
  TablePrefix: douyin_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
  FeedPageSize: 30
JWT:
  Secret: 666666
Oss:
  Endpoint: https://oss-cn-hangzhou.aliyuncs.com
  AccessKeyId: LTAI5tKB8DQcNebbWEsTwMn8
  AccessKeySecret: mqDn2frxVNx4EedzBIBUHIGa3i5Vew
  DefaultBucketName: view6view-douyin
  UrlPathPrefix: https://view6view-douyin.oss-cn-hangzhou.aliyuncs.com/