#配置文件
Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 6000
  WriteTimeout: 6000
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: root  # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: douyin_service
  TablePrefix: douyin_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
  FeedPageSize: 10
JWT:
  Secret: 666666
Oss:
  Endpoint: your_Endpoint
  AccessKeyId: your_AccessKeyId
  AccessKeySecret: your_AccessKeySecret
  DefaultBucketName: your_BucketName
  UrlPathPrefix: your_OssUrlPathPrefix